module.exports = {
  apps: [
    {
      name: 'hopcode-pty',
      script: '/home/jack/coding/voice-terminal/start-pty.sh',
      cwd: '/home/jack/coding/voice-terminal',
      autorestart: true,
      watch: false,
    },
    {
      name: 'hopcode-ui',
      script: '/home/jack/coding/voice-terminal/start-ui.sh',
      cwd: '/home/jack/coding/voice-terminal',
      uid: 'hopcode',
      gid: 'hopcode',
      autorestart: true,
      watch: false,
      env: {
        HOME: '/home/hopcode',
        AUTH_PASSWORD: 'myvoxterm18!',
        WECOM_BOT_ID: 'aib0o1yXItTA4yx1yltr-2mz4wEU4tTUVOI',
        WECOM_BOT_SECRET: 'nGz2ixhFwqw9cjJNuK2IZo4aZ5ISTu1GTj9eHMDQi59',
        WECOM_BOT_ID_2: 'aibpzIqbrBSOrZ5h2jb60B9iLY9UrAcDoRq',
        WECOM_BOT_SECRET_2: 'rNMJMOecpJ8kFkosYGrJhipFOUvu4tyllsJjXz3gAX6',
        VOLCANO_APP_ID: '7564153230',
        VOLCANO_TOKEN: 'tCVvm5UT-Dd0PglGVqTBzJoWSgjF1QNu',
        VOLCANO_RESOURCE_ID: 'seed-tts-2.0',
        VOLCANO_VOICE: 'zh_female_vv_uranus_bigtts',
        USER_WECOM_ID: '001',
        CLAUDE_BIN: '/usr/bin/claude',
      },
    },
    {
      name: 'browser-proxy',
      script: 'server.ts',
      interpreter: 'bun',
      cwd: '/root/browser-proxy',
      autorestart: true,
      watch: false,
    },
    {
      name: 'wechat-service',
      script: 'service.ts',
      interpreter: 'bun',
      cwd: '/root/wechat-service',
      autorestart: true,
      watch: false,
    },
  ],
};
